# -----------------------------------------------------------------------------
# BUILDER
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim AS builder

# Set the poetry env
ENV POETRY_VIRTUALENVS_CREATE=true
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_CACHE_DIR=/tmp/poetry_cache

# Copy project files
COPY .. /app

# Move to workdir
WORKDIR /app

# Install poetry and python dependancies
RUN pip install poetry==1.7.1 --root-user-action=ignore && \
    poetry install

# -----------------------------------------------------------------------------
# RUNTIME
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim AS runtime

ARG USER_NAME=knowledge-flow-user
ARG USER_ID=1000
ARG GROUP_ID=1000

# Setup user
RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m ${USER_NAME}

# Change user
USER ${USER_NAME}

# Copy source from builder
COPY --from=builder --chown=${USER_ID}:${GROUP_ID} /app /app

# Move to workdir
WORKDIR /app

# Activate the virtualenv
ENV PATH="/app/.venv/bin:$PATH"

# Expose Fast API default port
EXPOSE 8111

ENTRYPOINT ["python", "/app/knowledge_flow_app/main.py"]