# -----------------------------------------------------------------------------
# Backend development image
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim

ARG USER_NAME=knowledge-flow-user
ARG USER_ID=1000
ARG GROUP_ID=1000

# Install dependencies
RUN apt-get update && \
    apt-get install -y git

# Copy project files
COPY .. /app

# Setup user
RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m ${USER_NAME} && \
    mkdir /opt/python && \
    chown -R ${USER_ID}:${GROUP_ID} /app /opt/python

# Change user
USER ${USER_NAME}

# Set the python virtual env into docker image
ENV VIRTUAL_ENV=/opt/python/venv
ENV POETRY_CACHE_DIR=/tmp/poetry_cache

# Move to workdir
WORKDIR /app

# Create python virtual env
RUN python -m venv ${VIRTUAL_ENV}

# Activate the virtualenv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install poetry and python dependancies
RUN pip install poetry==1.7.1 && \
    poetry install && \
    rm -rf $POETRY_CACHE_DIR

# Expose Fast API default port
EXPOSE 8111

ENTRYPOINT ["python", "/app/knowledge_flow_app/main.py"]