_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  users:
    - "admin"
  backend_roles:
    - "opensearch_admin"

bidgpt_rw_role:
  reserved: false
  users:
    - "bidgpt_rw"
  backend_roles:
    - "opensearch_editor"

bidgpt_ro_role:
  reserved: false
  users:
    - "bidgpt_ro"
  backend_roles:
    - "opensearch_viewer"
