_meta:
  type: "roles"
  config_version: 2

bidgpt_ro_role:
  index_permissions:
    - index_patterns:
        - "bidgpt-dev-metadata"
      allowed_actions:
        - "read"

bidgpt_rw_role:
  index_permissions:
    - index_patterns:
        - "bidgpt-dev-metadata"
      allowed_actions:
        - "read"
        - "write"
